### ISSUE TITLE
Add a "TimeWalker" to enable keyboard and VR navigation of scene

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/building-mill-valley-ca-the-old-mill#8]
Hoping to get Eric Boise's help with this!

**Comment by damosuzuki** [comment]
This issue should probably be moved to the platform (/timewalk) and implemented there. The goal is to implement one or more FPCs so we can remove our dependency on the FPC in Standard Assets.

**Comment by damosuzuki** [comment]
The relevant platform ticket is here https://github.com/TimeWalkOrg/timewalk/issues/5

**Comment by damosuzuki** [comment]
Closing in favor TimeWalkOrg/timewalk#5
